### ISSUE TITLE
Partially missing modality

### ISSUE THREAD

**Issue by rezazad68** [Wangyixinxin/ACN#1]
Thanks for your implementation. The implemented code utilizes two networks for full modality and single modality (for example T1ce). After training the network it can work on only data with T1ce modality. How do you predict results for test samples with two modalities (for example T1 and Flair)? It seems to me that for each setting you need to train the code again, am I right?

**Comment by Wangyixinxin** [comment]
Hi, you are right. Our method is a 'one-stop-shop' solution and each model is dedicated to each missing situation. You can modify [line](https://github.com/Wangyixinxin/ACN/blob/main/train_val_ACN.py#L90-L91) and [line](https://github.com/Wangyixinxin/ACN/blob/main/models/build.py#L21) to train the corresponding models.

**Comment by rezazad68** [comment]
@Wangyixinxin Thanks for the guidance. Highly useful indeed.
