### ISSUE TITLE
Hello, what is the reason for Nan? Is the server configured as 2080ti 11g able to run programs?

### ISSUE THREAD

**Issue by zzmm711** [Wangyixinxin/ACN#3]

**Comment by Wangyixinxin** [comment]
Hi, we trained the model on V100 32g, but it should work on your server. Did you change any codes or the parameters? You could also check if the input data is correct and when the loss becomes Nan.

**Comment by zzmm711** [comment]
Thank you very much for your reply! On the premise of not changing the code, training the data will show that there is not enough memory. Would you like to ask how to run on a graphics card with 11g memory?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Wangyixinxin/ACN] Hello, what is the reason for Nan? Is the server configured as 2080ti 11g able to run programs? (#3)





 
Hi, we trained the model on V100 32g, but it should work on your server. Did you change any codes or the parameters? You could also check if the input data is correct and when the loss becomes Nan.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wangyixinxin** [comment]
You can try to train with just part of the data or decrease the Input size.
