### ISSUE TITLE
Can you share inference code?

### ISSUE THREAD

**Issue by pjw1** [Wangyixinxin/ACN#6]
Hi!
Thank you for sharing the code!

Now I am training your code and it runs well.
But I couldn't find inference code that load checkpoint, inference using validation loader, and calculate DICE score.

Do we have to code it ourselves?
If you have this code, can you share this one?

And, can you tell me how many epochs and time you train to get the results on the paper? (BraTS 2018)

Thank you in advance!

**Comment by Wangyixinxin** [comment]
Hi, thanks for the questions. 

The results of each epoch will be automatically saved in ./logs/ folder. For inference of other data set, you can just modify [this function](https://github.com/Wangyixinxin/ACN/blob/main/train_val_ACN.py#L27) and [this function](https://github.com/Wangyixinxin/ACN/blob/main/train_val_ACN.py#L43). You can calculate DICE score by yourself easily and you can also refer to [this issue](https://github.com/Wangyixinxin/ACN/issues/2#issuecomment-903122618). Please do calculate the correct region. 

We use the last training epoch (300) and the training time is about 2 days on V100 gpu. :)
