### ISSUE TITLE
controal missing modality

### ISSUE THREAD

**Issue by guanhdrmq** [Wangyixinxin/ACN#7]
Hi, can you kindly point out where you set singe-modality and multi-modality in your code? many thanks

**Comment by Wangyixinxin** [comment]
Hi, so sorry for the late reply. 

During the training phase, two networks are trained together (One for multi-modality and the other for single-modality). You can directly use the trained single-modality model if you only need to predict on single-modality data. I think your question is similar to this issue #1.  Let me know if you have further questions.

Best.
